labels: ["idea", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for a new feature? Share it here to get community feedback before creating a formal feature request!

  - type: textarea
    id: idea-description
    attributes:
      label: Feature Idea
      description: Describe your feature idea
      placeholder: What's your idea? How would it work?
    validations:
      required: true

  - type: textarea
    id: problem-solving
    attributes:
      label: Problem It Solves
      description: What problem would this feature solve?
      placeholder: What challenge or pain point would this address?
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would you use this feature?
      placeholder: Describe a specific scenario where this would be helpful
    validations:
      required: true

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which part of the app would this affect?
      options:
        - Dashboard
        - Habit Management
        - Progress Tracking
        - Settings
        - Mobile Experience
        - Data Management
        - User Interface
        - Other
    validations:
      required: true

  - type: textarea
    id: inspiration
    attributes:
      label: Inspiration
      description: Have you seen this feature in other apps? Any examples or inspiration?
      placeholder: Links to examples or descriptions of similar features

  - type: checkboxes
    id: community-input
    attributes:
      label: Community Input
      description: What kind of feedback are you looking for?
      options:
        - General thoughts on the idea
        - Suggestions for improvement
        - Similar experiences or needs
        - Technical feasibility input
        - Alternative approaches