labels: ["question", "help wanted"]
body:
  - type: markdown
    attributes:
      value: |
        Need help with Elevate? Ask your question here and the community will help you out!

  - type: dropdown
    id: help-category
    attributes:
      label: Help Category
      description: What do you need help with?
      options:
        - Getting started
        - Using a specific feature
        - Troubleshooting an issue
        - Best practices
        - Data management
        - Customization
        - Mobile usage
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What do you need help with?
      placeholder: Describe your question or what you're trying to accomplish
    validations:
      required: true

  - type: textarea
    id: what-tried
    attributes:
      label: What Have You Tried?
      description: What have you already tried to solve this?
      placeholder: Describe any steps you've already taken or solutions you've attempted

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any additional context that might be helpful
      placeholder: |
        - How long have you been using Elevate?
        - How many habits do you track?
        - What device/browser are you using?
        - Any specific goals or use cases?

  - type: checkboxes
    id: urgency
    attributes:
      label: Urgency
      description: How urgent is this question?
      options:
        - label: This is blocking me from using Elevate effectively
        - label: This would improve my experience but isn't urgent
        - label: This is just curiosity or future planning