name: ♿ Accessibility Issue
description: Report accessibility problems or barriers
title: "[A11y]: "
labels: ["accessibility", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping make Elevate accessible to everyone! Accessibility issues are important and will be prioritized.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this hasn't been reported
          required: true
        - label: I have tested this on the latest version of Elevate
          required: true

  - type: textarea
    id: accessibility-issue
    attributes:
      label: Accessibility Issue Description
      description: Describe the accessibility barrier or problem you encountered
      placeholder: What accessibility issue are you experiencing? What makes it difficult to use?
    validations:
      required: true

  - type: dropdown
    id: accessibility-category
    attributes:
      label: Accessibility Category
      description: What type of accessibility issue is this?
      multiple: true
      options:
        - Keyboard navigation
        - Screen reader compatibility
        - Color contrast
        - Focus management
        - Alternative text for images
        - Form labels and instructions
        - Heading structure
        - ARIA labels and roles
        - Text size and readability
        - Motion and animations
        - Other (please specify)
    validations:
      required: true

  - type: dropdown
    id: assistive-technology
    attributes:
      label: Assistive Technology Used
      description: What assistive technology are you using?
      multiple: true
      options:
        - Screen reader (NVDA)
        - Screen reader (JAWS)
        - Screen reader (VoiceOver)
        - Screen reader (TalkBack)
        - Screen reader (Other)
        - Voice control software
        - Switch navigation
        - Keyboard only navigation
        - Screen magnification
        - High contrast mode
        - Other (please specify)
        - None - testing for accessibility

  - type: input
    id: at-version
    attributes:
      label: Assistive Technology Version
      description: What version of assistive technology are you using?
      placeholder: e.g., "NVDA 2023.3", "VoiceOver on macOS 14", "TalkBack on Android 13"

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this accessibility issue?
      placeholder: |
        1. Navigate to '...'
        2. Use [assistive technology] to '...'
        3. Notice that '...'
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Accessible Behavior
      description: What should happen for this to be accessible?
      placeholder: Describe what the accessible experience should be like
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happens that creates the accessibility barrier?
      placeholder: Describe the current inaccessible behavior
    validations:
      required: true

  - type: dropdown
    id: wcag-guideline
    attributes:
      label: WCAG Guideline
      description: If you know which WCAG guideline this relates to, please select it
      options:
        - "1.1 Text Alternatives"
        - "1.2 Time-based Media"
        - "1.3 Adaptable"
        - "1.4 Distinguishable"
        - "2.1 Keyboard Accessible"
        - "2.2 Enough Time"
        - "2.3 Seizures and Physical Reactions"
        - "2.4 Navigable"
        - "2.5 Input Modalities"
        - "3.1 Readable"
        - "3.2 Predictable"
        - "3.3 Input Assistance"
        - "4.1 Compatible"
        - "Not sure"

  - type: dropdown
    id: severity
    attributes:
      label: Impact Severity
      description: How severely does this impact accessibility?
      options:
        - Low - Minor inconvenience, alternative methods available
        - Medium - Significant barrier, but workarounds exist
        - High - Major barrier, difficult to use feature
        - Critical - Complete barrier, feature is unusable
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: Browser
      description: Which browser(s) are you experiencing this issue on?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Opera
        - Other (please specify in additional context)
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: e.g., Windows 11, macOS 14, Ubuntu 22.04, iOS 17, Android 13
    validations:
      required: true

  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested Solution
      description: If you have ideas for how to fix this accessibility issue, please share them
      placeholder: Any suggestions for making this more accessible

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the accessibility issue
      placeholder: Screenshots, recordings, or additional details that might help

  - type: checkboxes
    id: testing-offer
    attributes:
      label: Testing Assistance
      description: Would you be willing to help test accessibility improvements?
      options:
        - label: I would be willing to test fixes for this accessibility issue
        - label: I would be interested in testing other accessibility improvements