name: 📚 Documentation Issue
description: Report problems with documentation or suggest improvements
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve Elevate's documentation! Clear documentation helps everyone use the app more effectively.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - README file
        - Installation instructions
        - Usage guide
        - Feature documentation
        - API documentation
        - Contributing guidelines
        - Code comments
        - Error messages
        - Help text in the app
        - Other (please specify)
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect information
        - Outdated information
        - Unclear or confusing
        - Typo or grammar error
        - Broken link
        - Missing examples
        - Needs more detail
        - Needs simplification
        - Other (please specify)
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Documentation Location
      description: Where is this documentation issue located?
      placeholder: |
        e.g., "README.md, Installation section"
        "Dashboard page, help tooltip for streak counter"
        "Settings page, export data description"
    validations:
      required: true

  - type: textarea
    id: current-content
    attributes:
      label: Current Content
      description: What does the current documentation say? (copy/paste if possible)
      placeholder: Paste the current text or describe what's currently there

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: What's wrong with the current documentation?
      placeholder: Describe the problem with the current documentation
    validations:
      required: true

  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Improvement
      description: How should this documentation be improved?
      placeholder: Provide your suggested text or describe what should be changed
    validations:
      required: true

  - type: dropdown
    id: target-audience
    attributes:
      label: Target Audience
      description: Who is the primary audience for this documentation?
      multiple: true
      options:
        - New users
        - Experienced users
        - Developers
        - Contributors
        - All users

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this documentation improvement?
      options:
        - Low - Minor improvement, not urgent
        - Medium - Would help users, should be addressed
        - High - Important for user experience
        - Critical - Blocking users or causing confusion
    validations:
      required: true

  - type: textarea
    id: user-impact
    attributes:
      label: User Impact
      description: How does this documentation issue affect users?
      placeholder: Describe how this impacts the user experience

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about this documentation issue
      placeholder: Screenshots, examples from other apps, or additional details

  - type: checkboxes
    id: contribution-interest
    attributes:
      label: Contribution Interest
      description: Would you be interested in helping improve this documentation?
      options:
        - label: I would be interested in writing or editing this documentation
        - label: I would be interested in reviewing documentation improvements